freifunk-berlin/bbb-configs

group_vars/all/imageprofile.yml

image profile: add vnstat

---

group_vars/all/wireless_profiles.yml
group_vars/location_colbe15/networks.yml
host_vars/colbe15-core/base.yml
roles/cfg_openwrt/templates/corerouter/config/dhcp.j2

introduce multiple dhcp networks

---

README.md

Add some documentation on the structure and where to add stuff and so on.

more verbose README

---

group_vars/target_ipq40xx_generic
roles/cfg_openwrt/tasks/conditional_packages.yml
roles/cfg_openwrt/tasks/main.yml
roles/cfg_openwrt/templates/common/config/irqbalance.j2

This PR supersedes #40 and fixes issue #67, which can be closed if this PR is merged.

ipq40xx/generic: Install irqbalance to improve performance

---

group_vars/location_fesev/networks.yml
host_vars/fesev-ap4/base.yml

add fesev-ap4

---

group_vars/location_fesev/networks.yml
group_vars/location_fesev/ssh-keys.yml

I added a ssh-key and Changed the channel of AP4 to a non DFS-channel because of #17

ssh-key added and new Channel Assignment

---

README.md

add notes on vlan-numbering

---

group_vars/location_gub37/networks.yml

The old IP space is too small, switch to a new bigger one.
```
IPv4 10.31.157.0/25
IPv6 2001:bf7:830:a700::/56
```

gub37: Grow IP-space to make space for gub37-zwingli

---

group_vars/location_gruni73/general.yml
group_vars/location_gruni73/networks.yml
group_vars/location_gruni73/owm.yml
group_vars/location_gruni73/snmp.yml
host_vars/gruni73-core/base.yml
host_vars/gruni73-nf-o-2ghz/base.yml
host_vars/gruni73-nf-so-5ghz/base.yml
host_vars/gruni73-nf-sw-2ghz/base.yml
host_vars/gruni73-nf-w-5ghz/base.yml

Add gruni73-core which is located on Grunbergerstr. 73, and will
be used to provide wifi coverage in most of Boxhagenerplatz.

Hello gruni73

---

group_vars/location_hirschhof/general.yml
group_vars/location_hirschhof/networks.yml
group_vars/location_hirschhof/owm.yml
group_vars/location_hirschhof/ssh-key.yml
group_vars/location_k12/general.yml
group_vars/location_k12/networks.yml
group_vars/location_k12/owm.yml
group_vars/location_k12/snmp.yml
group_vars/location_k12/ssh-key.yml
group_vars/location_k12_haus4/general.yml
group_vars/location_k12_haus4/networks.yml
group_vars/location_k12_haus4/owm.yml
group_vars/location_k12_haus4/ssh-key.yml
group_vars/model_tplink_archer_c5_v1.yml
group_vars/model_tplink_archer_c7_v5.yml
group_vars/model_tplink_cpe210_v1.yml
group_vars/model_tplink_cpe510_v1.yml
host_vars/hirschhof-core/base.yml
host_vars/hirschhof-k12/base.yml
host_vars/k12-ap1/base.yml
host_vars/k12-ap2/base.yml
host_vars/k12-core/base.yml
host_vars/k12-cpe/base.yml
host_vars/k12-haus4-core/base.yml
host_vars/k12-haus4-hirschhof/base.yml

added k12-haus4 and hirschhof - do not merge yet, still some issues with ethernet / vlans

hello k12 & hirschhof

---

group_vars/location_strom/networks.yml
group_vars/location_strom/owm.yml
group_vars/model_ubnt_nanostation_loco_m5_xm.yml
host_vars/strom-gw/base.yml
host_vars/strom-gw/gateway.yml
host_vars/strom-gw/owm.yml
host_vars/strom-so-2ghz/base.yml
host_vars/strom-so-5ghz/base.yml
host_vars/strom-sw-5ghz/base.yml

add strom gw

---

roles/cfg_openwrt/templates/common/rc.local.j2

Der letzte Ansible task, der noch nicht deterministisch ist. Damit ist alles grün/türkis.
```
PLAY RECAP ************************************************************************************************************************************************************************************************************************************
agym-core                  : ok=23   changed=0    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
ak36-gw                    : ok=22   changed=0    unreachable=0    failed=0    skipped=7    rescued=0    ignored=0   
b0russia-core              : ok=25   changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   
b90gruene-core             : ok=23   changed=0    unreachable=0    failed=0    skipped=6    rescued=0 …
```

templates: rc: make crontab time deterministic

---

group_vars/location_huette/networks.yml
group_vars/location_huette/ssh-key.yml
group_vars/location_huette/ssh-keys.yml
group_vars/location_huette15/networks.yml
group_vars/location_huette15/ssh-keys.yml

- add @pktpls ssh key
- codify our wifi settings
- remove mentions of huette15-vm

Maintenance huette & huette15

---

host_vars/zwingli-nord-nf-5ghz/base.yml

Signed-off-by: Robert Foss <robert.foss@linaro.org>

zwingli: Switch nord-nf-5ghz to Mikrotik SXTsq 5 AC

---

group_vars/location_hds/networks.yml
group_vars/location_hds/snmp.yml

hds-core: update mesh IP's

---

group_vars/location_segen/airos_dfs_reset.yml
group_vars/location_segen/general.yml
group_vars/location_segen/networks.yml
group_vars/location_segen/owm.yml
group_vars/location_segen/snmp.yml
group_vars/location_segen/ssh-key.yml
host_vars/segen-core/base.yml
host_vars/segen-n-nf-2ghz/base.yml
host_vars/segen-o-nf-2ghz/base.yml
host_vars/segen-s-nf-2ghz/base.yml
host_vars/segen-w-nf-2ghz/base.yml

Pull request based on feedback and requested changes from https://github.com/freifunk-berlin/bbb-configs/pull/203

hello segen

---

group_vars/location_fffw_lebenshilfe/networks.yml

This commit fixes minor linting-issues spotted out in #245

fuerstenwalde: adjust files to comply with linting

---

group_vars/location_f17/general.yml
group_vars/location_f17/networks.yml
group_vars/location_f17/owm.yml
group_vars/location_f17/snmp.yml
group_vars/location_f17/ssh-keys.yml
host_vars/f17-core/base.yml

f17: initial config

---

.github/workflows/ansible-lint.yml
.github/workflows/testbuild.yml
.github/workflows/yaml-lint.yml
play.yml
roles/cfg_openwrt/tasks/imagebuilder.yml

replacement for #256 that does not require disabling the warning for the whole project

fix yamllint truthy warnings

---

group_vars/location_perleberger36/general.yml
group_vars/location_perleberger36/networks.yml
group_vars/location_perleberger36/owm.yml
group_vars/location_perleberger36/snmp.yml
host_vars/perleberger36-core/base.yml
roles/cfg_openwrt/tasks/imagebuilder.yml

The core is a MikroTik RouterBOARD 450G

hello perleberger36

---

group_vars/location_kiehlufer/general.yml
group_vars/location_kiehlufer/networks.yml
group_vars/location_kiehlufer/snmp.yml

[squash together commits and fix snmp]

kiehlufer-core: rebuild & refactor

---

DEVELOPER.md

just added an example block for wireguard tunnels

extended DEVELOPERS.md with tunnel config

---

group_vars/location_philmel/airos_dfs_reset.yml
group_vars/location_philmel/networks.yml
group_vars/location_philmel/snmp.yml
host_vars/philmel-core/base.yml

This completes the move to the new ansible configuration for phimel.
Please wait with merge till I was able to test the setup on a local router.

Renumber IPv4+6 address on philmel

---

.github/workflows/shellcheck-lint.yml
roles/cfg_openwrt/files/common/init.d/replace_secrets
roles/cfg_openwrt/files/common/prom-catalog-register.sh

repo needs some work before this pull request can be merged.

add ShellCheck Linter

---

group_vars/model_mikrotik_routerboard_760igs.yml
host_vars/f17-core/base.yml

- including a definition for the Mikrotik Routerboard 760igs / HEX-S

f17: update switch hardware to Mikrotik HEX-S

---

group_vars/location_kiehlufer/networks.yml

Kiehlufer: update emma link

---

requirements.txt
roles/cfg_openwrt/tasks/conditional_packages.yml
roles/cfg_openwrt/tasks/imagebuilder.yml
roles/cfg_openwrt/tasks/render_etc.yml

This fixes the linter issues introduced by newer versions of ansible-lint and updates the required version of ansible-lint

ansible-lint: fix issues from new linter version

---

group_vars/all/wireless_profiles.yml
group_vars/location_dragonkiez_buero/networks.yml
group_vars/location_dragonkiez_buero/owm.yml
group_vars/location_dragonkiez_buero/snmp.yml
host_vars/dragonkiez-buero/base.yml

dragonkiez-buero

---

host_vars/rixbox-core/base.yml
roles/cfg_openwrt/tasks/main.yml
roles/cfg_openwrt/templates/common/config/poemgr.j2

poemgr: update for power budget patches

---

roles/cfg_openwrt/files/common/prom-catalog-register.sh

This has a few advantages:
- we always get the same IP, no matter what the default route is
- we don't need a default route
- we don't require a random internet service to be available

prometheus: derive our own IP from our config

---

roles/cfg_openwrt/files/common/prom-catalog-register.sh

Obviously the CIDR should be removed

prometheus: fix IP address format

---

group_vars/location_kiehlufer/networks.yml
host_vars/kiehlufer-huette/base.yml
host_vars/kiehlufer-nf-wbp4/base.yml

There's more peers in the backyard now, so a proper sector antenna makes sense

kiehlufer: add rocket for huette meshing

---

group_vars/all/wireless_profiles.yml
host_vars/cafe-wostok-ap1/base.yml
host_vars/cafe-wostok-ap2/base.yml
host_vars/cafe-wostok-core/base.yml
host_vars/gub37-hof-s/base.yml
host_vars/gub37-hof-w/base.yml
host_vars/magda-ap-remise/base.yml
host_vars/magda-ap1/base.yml
host_vars/magda-ap2/base.yml
host_vars/magda-ap3/base.yml
host_vars/magda-ap4/base.yml
host_vars/wilgu10-east-nf-2ghz/base.yml
host_vars/wilgu10-east-nf/base.yml
host_vars/wilgu10-west-nf/base.yml

i've encountered zero issues, even the owe usage rate increased, because it is taken automatically when available.
fixes #237

make owe transition wireless profile the new default

---

group_vars/location_elsekiehl/owm.yml

elsekiehl: update GPS coordinates

---

group_vars/location_kiehl71/owm.yml

kiehl71: update GPS coordinates

---

group_vars/model_tplink_archer_c6_v2.yml
group_vars/model_tplink_eap225_outdoor_v1.yml
roles/cfg_openwrt/tasks/main.yml

I'm running out of ideas, lets try candela tech driver on the affected devices.

[RFT] use ath10k-ct on unstable qca9886 radios

---

group_vars/location_dragonkiez_adlerhalle/general.yml
group_vars/location_dragonkiez_adlerhalle/networks.yml
group_vars/location_dragonkiez_adlerhalle/owm.yml
group_vars/location_dragonkiez_adlerhalle/snmp.yml
group_vars/location_dragonkiez_buero/general.yml
group_vars/location_dragonkiez_buero/networks.yml
group_vars/location_dragonkiez_dorfplatz/general.yml
group_vars/location_dragonkiez_dorfplatz/networks.yml
group_vars/location_dragonkiez_dorfplatz/owm.yml
group_vars/location_dragonkiez_dorfplatz/snmp.yml
group_vars/location_dragonkiez_rathausblock_miami/general.yml
group_vars/location_dragonkiez_rathausblock_miami/networks.yml
group_vars/location_dragonkiez_rathausblock_miami/owm.yml
group_vars/location_dragonkiez_rathausblock_miami/snmp.yml
group_vars/model_ubnt_unifiac_mesh.yml
host_vars/dragonkiez-adlerhalle/base.yml
host_vars/dragonkiez-dorfplatz-ap1/base.yml
host_vars/dragonkiez-dorfplatz/base.yml
host_vars/dragonkiez-rathausblock-miami-ap1/base.yml
host_vars/dragonkiez-rathausblock-miami-ap2/base.yml
host_vars/dragonkiez-rathausblock-miami/base.yml

There will be, in the next days, new networks in the dragonerarial.  These commits accomplish this task

Dragonkiez more networks

---

DEVELOPER.md

Unified formatting and added convention about commenting reserved addresses in networks.yml

DEVELOPER.md: Unified formatting and added convention in networks.yml

---

group_vars/location_philmel/networks.yml

Minor maintenance adjustments followed by creation of a new mesh interface for 60ghz test.

philmel: added mesh and changed names and comments

---

.github/workflows/ansible-lint.yml
.github/workflows/shellcheck-lint.yml
.github/workflows/testbuild.yml
.github/workflows/yaml-lint.yml

workflows: update checkout action to v3

---

group_vars/all/wireless_profiles.yml

OWE is buggy. Remove it until we were able to fix everything.

wireless: remove owe transition

---

group_vars/all/imageprofile.yml
roles/cfg_openwrt/tasks/conditional_packages.yml

treewide: add debugging-tools and order alphabetically

---

group_vars/location_cafe_wostok/networks.yml
host_vars/cafe-wostok-ap2/base.yml
host_vars/cafe-wostok-core/base.yml

- change upload to Easybell VDSL
- reduce tunnel connections to one
- remove devices that weren't installed (ap2, switch, ap-front)

cafe-wostok: update to DSL uplink

---

group_vars/model_mikrotik_routerboard_wap_g_5hact2hnd.yml
group_vars/model_tplink_archer_c5_v1.yml
group_vars/model_tplink_archer_c7_v5.yml
group_vars/model_tplink_cpe210_v1.yml

run tested the devices at locations k11, k12, hirschhof. looks good so far.

models: switch multiple devices to 23.05

---

group_vars/location_dragonkiez_plangarage/networks.yml

The new image is already installed and running
Fixes #483

dragonkiez-plangarage: fix dhcp netz

---

group_vars/location_rhxb/networks.yml
group_vars/location_rhxb/snmp.yml

There are 6 clients which currently use connections which are poor quality.  This adds a new dish which will serve the dragonerareal

rhxb: add dragon

---

group_vars/location_dragonkiez_adlerhalle/snmp.yml

small but import change for the statistics

dragonkiez-adlerhalle: fix snmp setup

---

.github/workflows/linter.yml
DEVELOPER.md
README.md

Update external links of the repository and Github docs.
Remove unavailable contact form link.

Update external links

---

group_vars/all/wireless_profiles.yml
group_vars/location_q216/general.yml
group_vars/location_q216/networks.yml
group_vars/location_q216/owm.yml
group_vars/location_q216/snmp.yml
group_vars/location_q216/ssh-keys.yml
host_vars/q216-core/base.yml
host_vars/q216-nf-s/base.yml

The SXTsq5ac still needs to be installed, the rest is up and running. Would like to already merge it so the config is visible for others.

q216: init

---

group_vars/location_bht/airos_dfs_reset.yml
group_vars/location_bht/networks.yml

Add airos_dfs_reset and update mesh metrics
This image is currently running on the node.

Bht airos dfs reset

---

roles/cfg_openwrt/templates/corerouter/config/firewall.j2

firewall: updated deprecated zone config

---

group_vars/location_mahalle/general.yml
group_vars/location_mahalle/networks.yml
group_vars/location_mahalle/owm.yml
group_vars/location_mahalle/ssh-keys.yml
host_vars/mahalle-core/base.yml
host_vars/mahalle-nf-o/base.yml
host_vars/mahalle-nf-w/base.yml

Hello Mahalle

---

roles/cfg_openwrt/templates/common/wikiupdater.j2

wikiupdater: fixed mails and matrixlinks.

---

group_vars/location_sama/networks.yml
group_vars/location_sama/snmp.yml

fixes the snmp profile for the wave ap
removes sama-zwingli

sama: fixes after wave ap install

---

group_vars/all/ssh-keys.yml

In my opinion, hener has proven that he is a committed and responsible member of our community. I suggest therefore we add his SSH key to the list of often trusted keys of all mayor locations.

all: add hener to list of trusted ssh keys

---

group_vars/location_zwingli/networks.yml

changed config to match current state

zwingli: correct current state

---

group_vars/location_b0russia/networks.yml
group_vars/location_forcki/networks.yml
group_vars/location_linksfraktiontk/networks.yml
group_vars/location_sonnenblume/networks.yml
group_vars/location_wuhli/networks.yml
host_vars/b0russia-core/base.yml
host_vars/forcki-core/base.yml
host_vars/linksfraktiontk-core/base.yml
host_vars/sonnenblume-core/base.yml
host_vars/wuhli-core/base.yml

Tunnel experienced enough testing. Switch to using tunspace.

b0russia,casa,forcki,sonnenblume,suedlbock,wuhli: use tunspace

---

vm.sh

Those paths were changed in #555 which was merged right before

vm: fix directory paths

---

group_vars/location_schreiner/networks.yml
group_vars/location_schreiner/snmp.yml

added proper assignments for antennas and poe switch

schreiner: fix assignments

---

locations/noki.yml

noki: init location

---

locations/huette15.yml

huette15: remove wifi, change to x86

---

group_vars/location_fesev/general.yml
group_vars/location_fesev/owm.yml
group_vars/location_fesev/snmp.yml
group_vars/location_fesev/ssh-keys.yml
host_vars/fesev-ap1/base.yml
host_vars/fesev-ap2/base.yml
host_vars/fesev-ap3/base.yml
host_vars/fesev-ap4/base.yml
host_vars/fesev-ap5/base.yml
host_vars/fesev-ap6/base.yml
host_vars/fesev-ap7/base.yml
host_vars/fesev-core/base.yml
locations/fesev.yml

- Convert to sfl
- remove ap7 as it never got installed
- add wifi-roaming

Fesev: Several changes

---

locations/spitta13.yml

location will be build up soon

spitta13: init location

---

group_vars/location_habersaath/general.yml
group_vars/location_habersaath/owm.yml
group_vars/location_habersaath/ssh-keys.yml
host_vars/habersaath-ap-a1/base.yml
host_vars/habersaath-ap-a2/base.yml
host_vars/habersaath-ap-a3/base.yml
host_vars/habersaath-ap-a4/base.yml
host_vars/habersaath-ap-a5/base.yml
host_vars/habersaath-ap-a6/base.yml
host_vars/habersaath-ap-b1/base.yml
host_vars/habersaath-ap-b2/base.yml
host_vars/habersaath-ap-b3/base.yml
host_vars/habersaath-ap-b4/base.yml
host_vars/habersaath-ap-b5/base.yml
host_vars/habersaath-ap-b6/base.yml
host_vars/habersaath-ap-c1/base.yml
host_vars/habersaath-ap-c2/base.yml
host_vars/habersaath-ap-c3/base.yml
host_vars/habersaath-ap-c4/base.yml
host_vars/habersaath-ap-c5/base.yml
host_vars/habersaath-ap-c6/base.yml
host_vars/habersaath-ap-d1/base.yml
host_vars/habersaath-ap-d2/base.yml
host_vars/habersaath-ap-d3/base.yml
host_vars/habersaath-ap-d4/base.yml
host_vars/habersaath-ap-d5/base.yml
host_vars/habersaath-ap-d6/base.yml
host_vars/habersaath-core/base.yml
host_vars/habersaath-w-nf-5ghz/base.yml
locations/habersaath.yml

converted the location into the single file location format and changed contact details to community as it is an communitymaintained location.

habersaath: converted to sfl and changed contact

---

group_vars/location_linie206/general.yml
group_vars/location_linie206/owm.yml
group_vars/location_linie206/ssh-keys.yml
host_vars/linie206-core/base.yml
host_vars/linie206-nf-o-5ghz/base.yml
host_vars/linie206-nf-s-5ghz/base.yml
host_vars/linie206-nf-so-2ghz/base.yml
host_vars/linie206-nf-so-5ghz/base.yml
host_vars/linie206-nf-w-2ghz/base.yml
host_vars/linie206-nf-w-5ghz/base.yml
host_vars/linie206-nf-wohnzimmer/base.yml
locations/linie206.yml

* converted to /locations
* added matrix-room as a contact
* fixed names in channel assignments

Linie206: converted to /locations and added Matrix-Room as Contact

---

locations/rhnk.yml

Added the new Wave AP towards Zwingli
Added SNMP monitoring, which should work with AF60 profile now

rhnk: added rhnk-nno-60ghz, minor fixes

---

locations/mlk-nk.yml

- config now matches the state of the location
- VLANs now match our convention
- corrected settings of so-antenna
- renamed antenna from zwingli to nno and made it an AP
- removed incorrect channel settings

mlk-nk: multiple changes and fixes

---

group_vars/location_wilgu10/networks.yml
locations/ak36.yml
roles/cfg_openwrt/templates/gateway/config/olsrd.j2

- implement olsrd nameservice assignments for mgmt hosts on gateways
- remove uisp assignment from wilgu10
- set olsrd nameservice assignments for ak36

migrate uisp to host within ak36

---

group_vars/model_glinet_gl_mt1300.yml

Enable image and config generation for the glinet gl mt1300 travel router

model file: add glinet gl mt1300

---

group_vars/location_jup/general.yml
group_vars/location_jup/owm.yml
group_vars/location_jup/snmp.yml
host_vars/jup-bar/base.yml
host_vars/jup-bullet-ap4/base.yml
host_vars/jup-core/base.yml
host_vars/jup-m2-ap3/base.yml
host_vars/jup-m5-ap1/base.yml
host_vars/jup-m5-ap2/base.yml
host_vars/jup-m5-ap5/base.yml
locations/jup.yml

Traffic was still going via that poor link, therefore make it worse to prefer routing via segen

jup: single file format & make bht link even worse

---

DEVELOPER.md

Rewrite of the file to account for the new standard of using single file locations. Added wireless profiles and some other smaller hints as well. It would make sense to write better docs for the profiles in the future.

DEVELOPER.md: Rewrite for locations/

---

locations/strom.yml
roles/cfg_openwrt/tasks/merge_vars.yml
roles/cfg_openwrt/templates/common/rc.local.j2

strom: disable eth0 hw offloads to work around bug

---

locations/fffw-rathaus.yml

This PR converts the existing Falter setup over to bbb-configs.

fffw-rathaus: init location

---

group_vars/location_linksfraktiontk/general.yml
group_vars/location_linksfraktiontk/owm.yml
host_vars/linksfraktiontk-core/base.yml
locations/linksfraktiontk.yml

Additionally i fixed a comment

Linksfraktiontk: converted to single file location

---

locations/bht.yml
locations/kub.yml
locations/scharni.yml

fixes #733, fixes #726, fixes #725

locations: fixing several small mistakes

---

locations/k12-haus1.yml
locations/k12-haus3.yml
locations/k12-haus4.yml
locations/k12.yml

added 2 new nodes, updated the locations for 2 existing nodes

k12: new nodes and updated locations

---

group_vars/location_mahalle/general.yml
group_vars/location_mahalle/owm.yml
group_vars/location_mahalle/ssh-keys.yml
host_vars/mahalle-core/base.yml
host_vars/mahalle-nf-o/base.yml
host_vars/mahalle-nf-w/base.yml
locations/mahalle.yml

I will add mac-overwrite and suggested owm-data in an extra pr.

mahalle: converted to single file location

---

locations/scharni.yml

- use different mgmt vlan 436
- remove the link penalty on sama link

scharni: update location after installing 60 ghz link

---

locations/kirchhof.yml

Is that enough? Do we need to change more of the wireless profile?

kirchhof: change prdhcp ssid

---

locations/rigaer78.yml

rigaer78: remove rigaer78-eap225

---

locations/kiehlufer.yml

- replace rocket witch zyxel
- enable 2.4 GHz meshing
- fix SNMP monitoring for wave nano

kiehlufer: fixes / changes

---

group_vars/model_tplink_archer_c7_v4.yml
locations/rev99.yml

This PR introduces rev99 as a new location.

rev99: init location

---

locations/cralle.yml

This is a very small location now. But there will be more APs in the future.
Will be merged as soon as it is deployed.

cralle: init location

---

mass-update.sh

This scripts aims to improve mass updates. The script checks for availability, free memory in comparison with the image size and a successful file transfer.
Note: This script will skip some low memory devices and could be improved so it could also flash these in the future, but for now I did not really care.

utilities: add mass update script

---

locations/segen.yml

Reflect the actual orientation of the antenna

segen: fix names

---

DEVELOPER.md

Was part of ilr-pr. Seperated by request of @Noki

developer.md: add description for dns option

---

locations/hirschhof.yml
locations/k11.yml
locations/k12-3v0s.yml
locations/k12-haus3.yml
locations/k12-haus4.yml
locations/k12.yml

Various config changes to clean up configs, replace core / add new nodes and APs.

K12 changes

---

.github/workflows/configrun.yml
.github/workflows/linter.yml
.github/workflows/wikiupdate.yml
DEVELOPER.md
roles/cfg_openwrt/files/packagefeed_master.pub
roles/cfg_openwrt/files/wiki/update.py

Please [edit the branch name](https://github.com/freifunk-berlin/bbb-configs/settings) and close [this issue](https://github.com/freifunk-berlin/bbb-configs/issues/646) when merging this PR

treewide: move to main branch as default branch

---

mass-update.sh

remove all host related files after flashing
reduce required memory

scripts: improve mass update

---

DEVELOPER.md
FAQ.md
README.md

* Added requirements. That fixes #796
* `DEVELOPER.md`
* Added missing options and explanations for model files
* Fixed typo
* `FAQ.md`
* Fixed "bring up a location" regarding the single file location changes.
* Simplified the linting-section

Docs: Updates and Additions

---

FAQ.md

As discussed [here](https://github.com/freifunk-berlin/bbb-configs/pull/867#discussion_r1677185212).

faq: added disclaimer for additional requirements

---

locations/teufelssecurity.yml

Mac overwrite for mesh ap needs to be added. I don't have access to a device right now.

teufelssecurity: add location

---

locations/spitta13.yml

spitta13: fix ipv6-Adress

---

.github/checks/check-hostname-duplicates.sh
.github/workflows/check-hostname-duplicates.yml
locations/dtmb.yml

This PR introduces a check to detect duplicate hostnames and fixes existing issues:

workflows: add hostname duplicate check / fix duplicates

---

.github/checks/check-address-duplicates.sh
.github/workflows/check-address-duplicates.yml
locations/kirchhof.yml

This PR checks introduces a check for address duplicates and fixes existing issues:

workflows: add address duplicate check / fix duplicates

---

group_vars/model_cudy_x6_v1.yml
locations/dragonkiez-adlerhalle.yml
locations/kub.yml
locations/suedblock.yml

- dragonkiez-adlerhalle is the last Unifi AC Mesh to be upgraded to 23.05
- kub's ap1 Fritzbox has broken wifi, replace with Cudy X6 (appointment this week)
- suedblock's Fritzbox has some issue which prevents upgrades, replace with Cudy X6 (appointment this week)

maintenance: suedblock, kub, dragonkiez-adlerhalle

---

.github/checks/check-vlan-duplicates.sh
.github/workflows/check-vlan-duplicates.yml

This PR adds duplication checks for VIDs and VLAN names

workflows: added VID / VLAN name duplication check

---

locations/linie206.yml

linie206: replace corerouter with Routerboard 750gr3

---

group_vars/role_gateway/imageprofile.yml

gateways: added collectd-mod-snmp to fix monitoring

---

locations/rigaer78.yml

rigaer78: fix channel assignments

---

locations/forcki.yml

fixes #782
Added a second tunnel and cleaned the config up a bit

forcki: added again

---

locations/emma.yml

In addition I changed the formatting a bit.

Emma: remove ono

---

locations/vaterhaus.yml

vaterhaus: add airos-dfs-reset config

---

locations/hacrafu-pici.yml

Resolves #1048 
Konnte #1048 nicht mergen, weil ich ihn nicht rebasen konnte, aber auch nicht von Hand mergen+pushen.

Push protection

---

group_vars/all/general.yml
group_vars/role_gateway/general.yml
group_vars/role_gateway/imageprofile.yml
roles/cfg_openwrt/templates/gateway/bird.conf.j2
roles/cfg_openwrt/templates/gateway/config/firewall.j2

Overhaul Metrics on the Gateways

---

group_vars/model_dlink_covr_x1860_a1.yml

Running now for 1 week without any issue on 24.10.

model: switch dlink_covr_x1860 to openwrt 24.10

---

locations/elsekiehl.yml
locations/kiehl71.yml
locations/wilde.yml

elsekiehl, kiehl71, wilde: upgrade to 24.10-SNAPSHOT

---

group_vars/model_tplink_archer_c50_v4.yml

modelfile: tp-link archer c50 v4

---

locations/sav.yml

Update mail sav.yml

---

locations/strom.yml

setup is basically the same as AK36-gw

give strom v6

---

roles/cfg_openwrt/templates/corerouter/config/tunspace.j2

Siehe https://github.com/freifunk-berlin/falter-packages/pull/464 - der support hier in bbb-configs sollte gemerget werden, bevor der Package Feed neugebaut ist.

tunspace: use new insecure_cert option

---

README.md

This PR tries to improves the README by restructuring it slighly so it is easier to consume.

documentation: improve README.md

---

locations/c-base.yml

c-base: add 2 more aps

---

locations/l105.yml

Setup ist gleich dem des akgw und stromgw

L105: IPv6 uplink

---

locations/c-base.yml

neue PTP antenne zur simeonskirche

C-base: add ptp for simeon

---

locations/genterstr69.yml

First config of genterstr69, it is already live

genterstr69: adding initial config

---

mass-update.sh

Add additional timeouts as sometimes the ssh connection was working, but the execution of the ssh command was not, causing the script to hang. In addition continue with other hosts instead of exiting the script.

scripts: improve mass-update.sh

---

DEVELOPER.md
FAQ.md
roles/cfg_openwrt/templates/common/config/network.j2

I updated the documentation
- Updated mass updates section to use the script instead
- Added section about hosting your services with bbb-configs
- Fixed some typos

Docs: Add section about running own services, updated mass updates section

---

locations/simeon.yml

simeon: add 60g sektor for nord ost (cbase)

---

locations/koepi.yml

Plug for one ptp needs to be redone, rest ist working

koepi: location rebuild, mostly devices removed or replaced

---

group_vars/model_genexis_pulse_ex400.yml

Model:  genexis pulse ex400

---

README.md

changed description to make it easier to get a short overview according to issue #1260

README: bbb-configs description changed

---

locations/l105.yml

L105 add 60GHz pointing to new node bissing

---

locations/bissing.yml

activate hardware offloading. thx to niclolas

Bissing, add hardware offloading

---

group_vars/model_ubnt_edgerouter_x_sfp_24_10.yml
locations/segen.yml

Replacement router needs to get installed before this can be merged.

segen: update to 24.10

---

group_vars/model_x86_64_bcrmfmac.yml
locations/fblipke.yml

This PR add the location and the used Model to bbb-configs.

FBLipke: Add Location
