requirements.txt

netaddr is required for generating some of the configurations

added missing netaddr requirement

---

group_vars/target_ipq40xx_generic
roles/cfg_openwrt/templates/common/rc.local.j2

Definining different cpu settings can result in performance increase
and reduction of latency/jitter.

ipq40xx: add option to define cpu_settings

---

roles/cfg_openwrt/templates/uplink_gateway/conntrackd/conntrackd.conf.j2

FTFW:
This mode is based on a reliable protocol that performs message
tracking. Thus, the protocol can recover from message loss, re-ordering
and corruption.
NOTRACK
Is the most simple mode as it is based on a best effort replication
protocol, ie. unreliable protocol. This protocol sends and receives
the state information without performing any specific checking.
Source: https://manpages.debian.org/testing/conntrackd/conntrackd.conf.5.en.html
We use samplicator with UDP so we should switch to NOTRACK.
Fixes: #96 (uplink_gateways: conntrackd goes bad)

uplink_gateway: switch to NOTRACK

---

host_vars/l105-gw/gateway.yml
host_vars/ohlauer-gw/gateway.yml
host_vars/saarbruecker-gw/gateway.yml
roles/cfg_openwrt/templates/common/config/network.j2
roles/cfg_openwrt/templates/uplink_gateway/config/babeld.j2
roles/cfg_openwrt/templates/uplink_gateway/config/network.j2

Fixes: #99 (" Why is the ipv6 prefix not assigned to lo-interface for up-link gateways?")

uplink: add ipv6 prefix to lo and redistribute

---

group_vars/role_uplink_gateway/imageprofile.yml
roles/cfg_openwrt/templates/uplink_gateway/config/dhcp.j2

Dnsmasq is important to resolve olsr addresses. Add it to uplink gateways.

uplink: add dnsqmasq to uplink gateways

---

roles/cfg_openwrt/templates/corerouter/config/dhcp.j2

templates: add dummy host to skip static dhcp leases
Sometimes we have static assignments. Add them as dummy hostnames to
dnsmasq.

templates: add dummy host to skip static dhcp leases

---

roles/cfg_openwrt/templates/common/config/system.j2

Fixes errors in the form of:
"The device is supported, but the config is incompatible to the new image ($devicecompat->$imagecompat). Please upgrade without keeping config (sysupgrade -n)."
The compat_version is missing so DSA targets are interpreted as 1.0
although they are 1.1.

templates: fix dsa sysupgrade

---

group_vars/all/general.yml
roles/cfg_openwrt/templates/common/config/freifunk.j2

As discussed earlier I changed the standard contact information.

general.yml: change default contact nickname and mail to info@berlin.*

---

group_vars/location_zwingli/networks.yml
group_vars/location_zwingli/snmp.yml

[zwingli: add 60 ghz antenna to vaterhaus](https://github.com/freifunk-berlin/bbb-configs/pull/140/commits/1c5801063008d18ce5499ff57c7c8f17f2001f29)
Move zwingli-emma to ".7" in the mgmt, and vlan to 18.
Add zwingli-vaterhaus on ".8" in the mgmt, and vlan 17.

zwingli: add 60 ghz antenna to vaterhaus

---

group_vars/location_gub37/networks.yml

This is necessary in order to prevent using mesh links for routing when
backbone links are available.

gub37: Lower link quality multiplier for mesh links

---

roles/cfg_openwrt/templates/common/config/wireless.j2

This commit fixes an issue introduced when https://github.com/freifunk-berlin/bbb-configs/commit/2e432f6286c6be7ed287b92a977d85a437f095d5 added length checking.
```
config wifi-iface 'radio0_if2'
option device 'radio0'
option ifname 'wlan5-mesh'
option mode 'mesh'
option mesh_id 'Mesh-Freifunk-Berlin'
option mesh_fwding '0'
option mcast_rate '12000'
Mesh name ok
option network 'mesh_11s_no5'
```
'Mesh name ok' is not mean to be in the above snippet, and causes a parsing issue. 
This commit fixes this syntax error, while keeping the length checking.

template: Fix bad syntax from length check

---

group_vars/role_ap/imageprofile.yml

With commit 58784281e939 ("corerouter: switch to nftables for mss
clamping") firewall4 was not longer removed from the whole package list.
The snapshot APs have firewall4 included by default and so we need to
explicitly remove it from their package list.

role_ap: fix firewall4 is installed

---

host_vars/gub37-hof-n-5/base.yml

Switch to a Mikrotik LHG 5 AC radio, which runs the same firmware as SXTsq 5 AC.

gub37: Switch out Hof Nord 5GHz radio

---

inventory/base_inventory

The inventory script was printing the host list unconditionally,
providing unneccessary metric tons of data to the gatherer.
We now properly implement the --list and --host options mandated by Ansible.
This gets us from >30s down to ~3s on my personal machine.
```sh
> time ansible-inventory --list >/dev/null
real 0m36,480s user 0m33,413s sys 0m9,379s
> time ansible-inventory --list >/dev/null
real 0m2,633s user 0m2,286s sys 0m0,420s
```
See https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#inventory-script-conventions

inventory: speed it up significantly

---

.github/workflows/testbuild.yml

If changes are applied not affecting any hosts or locations, all hosts were built. However, github was frequently aborting that run.Instead of building all hosts, we only build an ap, core and a gateway.

workflows: build dummy hosts if no host changed

---

group_vars/location_gruni73/networks.yml

Dodge busy 2ghz channel. Avoid 5ghz channels that overlap with uplink radios.

Gruni73 channels

---

group_vars/location_gruni73/networks.yml
host_vars/gruni73-nf-sw-5ghz/base.yml

This configuration adds the currently deployed gruni73-nf-sw-5ghz host, which uses a Rocket AC Lite radio + Titanium antenna.
This host is deployed as an experiment to try to narrow down the poor radio performance that is seen at the gruni73 location.

gruni73: Add experimental nf-sw-5ghz radio

---

roles/cfg_openwrt/templates/common/dropbear/authorized_keys.j2

This replaces the comment from the original ssh-key with the comment of the yml file, which is the name of the user. This labels keys without a comment with a proper username so it can easily be identified on the router and removes useless information like machine names from the file. The original comment can still be kept in the git repository, where it might be useful to the owner of the key to identify his key.

use comments from yml file for generation of authorized_keys

---

roles/cfg_openwrt/templates/common/config/system.j2

On some sites the airos devices are configured to get the time from
the core router. Enable the server on core-router and uplink-gateway.

corerouter/gateway: enable ntp server

---

roles/cfg_openwrt/templates/corerouter/config/babeld.j2
roles/cfg_openwrt/templates/uplink_gateway/config/babeld.j2

With the now enabled link quality estimation, we should leave the rxcost untouched for now, as this is the base which will be multiplied if packetloss is detected. 
Our metric is now explicitly added to the calculated metric.

babel: rework metrik; use filter, leave rxcost vanilla

---

roles/cfg_openwrt/templates/common/config/naywatch.j2

We need to give the interface names (mgmt) instead of the device names
(lan0.42).

naywatch: fix naywatch

---

group_vars/model_linksys_e8450_ubi.yml

OpenWrt moved wolfssl from packages to main repository. However, the
package feed is now invalid. Go to openwrt-snapshot again.

linsys-e8450: fix building images

---

group_vars/location_segen/owm.yml

The current position is inaccurate and hopglass shows the position marker on the street. This fixes the position so it points to the center of the tower of the church.

segen: more accurate geo position

---

group_vars/role_uplink_gateway/ssh-key.yml

The gateways which are sponsored by the förderverein schould be
accessible by it.

Gateways: add ssh-key for dpaufler

---

.config/ansible-lint.yml
.config/yaml-lint.yml
.github/workflows/ansible-lint.yml
.github/workflows/testbuild.yml
.github/workflows/yaml-lint.yml
FAQ.md
requirements.txt

ansible-lint uses yamllint to lint yaml files but does not allow a custom config for yamllint e.g. to configure or ignore line length. this commit fixes this by adding yamllint as a standalone linter with its own config

add yamllint as a standalone linter with its own config

---

group_vars/all/imageprofile.yml

The plugin scrape the mac addresses of client stations. Remove them.
I am sure there is a way to disable the scraping of mac addresses. However, that needs additional coding. Remove them until it is fixed.

all: remove plugins that scrape mac addresses 

---

group_vars/all/imageprofile.yml
group_vars/model_ubnt_edgerouter_4.yml
group_vars/model_ubnt_nanostation_loco_m5_xm.yml

This will reduce the load on openwrt servers.

treewide: use cdn.openwrt for downloads

---

group_vars/all/imageprofile.yml
roles/cfg_openwrt/tasks/imagebuilder.yml

First two are about easier debugging (I'm sure @pmelange stumbled upon these the other day), third is about faster turnaround times, fourth fixes a race condition during images/ cleanup.
commit ddf33d0eb05974d13199a389e4182d999e964a7e
Author: Packet Please <pktpls@systemli.org>
Date:   Mon Aug 15 01:05:25 2022 +0200
imagebuilder: work around Imagebuilders inconsistent exit codes
Imagebuilder seems to correctly exit non-zero for some errors
(e.g. opkg install) and simply skip over other errors (e.g. from
squashfs image manipulation).
The latter resulted in confusing "declare source" error messages
which were hard to track down to their cause.
We now check that there's an actual image built, and don't rely
only on Imagebuilder's exit code for error reporting.
commit …

Imagebuild smallies

---

group_vars/location_rixbox/general.yml
group_vars/location_rixbox/networks.yml
group_vars/location_rixbox/owm.yml
group_vars/location_rixbox/snmp.yml
group_vars/location_rixbox/ssh-keys.yml
group_vars/model_ubnt_usw_flex.yml
host_vars/rixbox-ap1/base.yml
host_vars/rixbox-ap2/base.yml
host_vars/rixbox-ap3/base.yml
host_vars/rixbox-core/base.yml
roles/cfg_openwrt/tasks/conditional_packages.yml
roles/cfg_openwrt/tasks/main.yml
roles/cfg_openwrt/templates/common/config/poemgr.j2

Rixbox Espresso & Food @ Karl-Marx-Straße / Alfred-Scholz-Platz - very nice MABB site from 2014 that got new gear.
This soft-depends on blocktrron/poemgr#5 - it builds correctly without this patch, but fails to power up all devices. We can merge anyway - we give priority to the Rixbox-RHNK uplink and leave the APs disabled. Then after first boot, we install the patched poemgr package and enable the APs.
The wiki has been updated to reflect the new setup: https://wiki.freifunk.net/Berlin:Standorte:Rixbox

Rixbox init

---

group_vars/location_bht/general.yml

This one was missed for quite a time. Please don't miss the
'i' at the beginning of the address! Using vim is no excuse
for that.

bht: correct Perrys Mail

---

.config/ansible-lint.yml
.config/yaml-lint.yml
FAQ.md
README.md

I added a quick info in regards to a virtualenv, since this should be the default when using python.
This way you don't collect dependencies from random projects in your homedir

Add the usage of a venv to the documentation

---

group_vars/model_ubnt_usw_flex.yml

Somehow Github didn't pick up this last change I pushed last night...
We don't need `low_flash` since removing `curl` saves enough disk space. We also require `opkg` which would be removed by `low_flash`.

usw-flex: we require opkg and don't need low_flash

---

requirements.txt

This pull request updates the requirements to the latest available versions to address errors that most likely occured due to outdated versions (#316).
ansible core has a newer version 2.13, older version are end of life
jmespath has now a stable 1.0.1 release
yamllint has an updated version 1.27.1

Update requirements.txt to match latest available versions

---

DEVELOPER.md
roles/cfg_openwrt/templates/common/config/wireless.j2

As described in the OpenWRT documentation (https://openwrt.org/docs/guide-user/network/wifi/basic) hwmode was replaced by band in 21.02.2. This PR introduces support for using band instead of hwmode and updates the documentation accordingly. For easy transitioning if present band will be used instead of hwmode, but hwmode will still work.

add support for wlan band replacing hwmode

---

.config/ansible-lint.yml
.gitignore

This pull requests fixes ansible-lint by skipping the template-insted-of-copy-rule and adds the venv directory to .gitignore.

Git & ansible-lint changes

---

DEVELOPER.md
roles/cfg_openwrt/templates/common/config/wireless.j2

This pull request adds support to specify an htmode_prefix that allows to specify the highes possible htmode for the wlan device. If accepted this should close #261.
What's missing is adding the setting for all models.

Add htmode prefix

---

roles/cfg_openwrt/templates/corerouter/config/tunnelmanager.j2

This should fix #308 and once merged #334 will add this to the documentation.

tunnelmanager: change default metric for client uplinks

---

group_vars/location_l105/general.yml

merging PR #320 broke accidentially the CI. Fixing that, by flagging l105-gw as community-site.

l105-gw: Add community-flag

---

group_vars/location_k11/networks.yml

Due to a collision with hand-crafted Museumsinsel, we change the prefixes to be unique again.

k11: Change prefixes

---

group_vars/location_huette15/networks.yml
group_vars/location_kts13/networks.yml

huette15 is getting new IP addresses because of a collision with Museumsinsel.
huette15 and kts13 are getting `tunnel_connections = 1` so we don't create multiple Wireguard tunnels there, might avoid funky routing business.

huette15, kts13: decrease number of tunnels, set new ip addrs

---

roles/cfg_openwrt/files/common/prom-catalog-register.sh

Due to space constraints, we don't install `ip-tiny` nor `ip-full` which provide JSON output. Instead we only have Busybox's `ip`, so we have to parse its output on our own.

prometheus: avoid ip --json

---

group_vars/location_gruni73/networks.yml

The mesh vlan entries were mistakenly removed in an earlier commit.
Fixes: 218ffb3 - gruni73: Remove Mikrotik SXTsq 2Ghz APs

gruni73: Fix mesh VLANs for uplink antennas

---

group_vars/location_rhnk/networks.yml
host_vars/rhnk-nf-bvv/base.yml
host_vars/rhnk-platz/base.yml

The most significant change is the `mgmt` network now being on VLAN 420. See #299.

rhnk: updates from Saturday

---

roles/cfg_openwrt/templates/common/config/freifunk.j2

Currently it would result in
```
info+zwingli-core@berlin.freifunk.net
```
But we agreed on using `info+$locationname@berlin.freifunk.net`

Fixup default contact email on community sites

---

group_vars/location_agym/general.yml
group_vars/location_dragonkiez_buero/general.yml
group_vars/location_grueni/general.yml
group_vars/location_habersaath/general.yml
group_vars/location_manstein10/general.yml
group_vars/location_newyorck/general.yml
host_vars/ak36-gw/general.yml
host_vars/ohlauer-gw/general.yml
host_vars/saarbruecker-gw/general.yml

- agym: community, stammt aus der MABB-Förderung, damals wurde das als Projekt zusammen mit einer AG an der Schule aufgebaut
- ak36: community, Zugang über den Speedbone-Kontakt oder die Amateurfunker
- habersaath: stadtfunk
- ohlauer: community, Zugang über up42 GmbH bzw. Hausmeister
- saarbruecker: community, Zugang über Hausmeister
---
- dragonkiez_buero: cc @pmelange you seem to be working with them
- grueni: cc @robertfoss this location can probably be removed?
- manstein10: wird von @ideesnoires gepflegt
- newyorck: wird von @noxilixon gepflegt, willst du eine

locations: add remaining missing contacts

---

group_vars/all/general.yml
group_vars/model_netgear_wax202.yml
group_vars/model_ubnt_edgerouter_x.yml
group_vars/model_ubnt_edgerouter_x_sfp.yml
group_vars/model_ubnt_usw_flex.yml
group_vars/model_zyxel_nwa55axe.yml
host_vars/scharni-ap-keller/base.yml
host_vars/scharni-ap-kneipe/base.yml
roles/cfg_openwrt/tasks/imagebuilder.yml
roles/cfg_openwrt/templates/common/config/system.j2

this involves hardcoding the resulting compat_version in the image metadata to 1.0 and also hardcoding it within the config. We dont need the compat_version check because we ship the config within the image.
If the device you are flashing is running at a higher compat_version you likely have to use sysupgrade -n in order to fix it again

get rid of compat_version checking

---

DEVELOPER.md
roles/cfg_openwrt/templates/common/config/system.j2

This pull request should address the remaining stuff to close #4.
To actually start using the NTP server on the core router the corresponding networks files have to be changed later on.

Make APs use NTP server of the core router

---

group_vars/location_dragonkiez_dorfplatz/networks.yml
group_vars/location_dragonkiez_rathausblock_miami/networks.yml

The length of the br-$NAME interfaces were too long and prevented the creation of the required bridge interfaces. This fixes those names.

dragonkiez: reduce name of mesh bridges

---

group_vars/model_tplink_tl_wdr4900_v1.yml

WDR4900 boots now with extra spi-loader.

model: wdr4900: bump wdr4900 to 22.03

---

group_vars/all/imageprofile.yml

This fixes conflicts of package dependencies which broke snapshot builds.

all: fix package conflicts on snapshot

---

host_vars/ak36-gw/gateway.yml

From as36s-hyp03 to the rooftop switch, mesh is on VLAN 14
mgmt ip 10.31.130.136
mesh ip 10.31.130.165 2001:bf7:750:4001::6/128

ak36-gw: add new radio to rhnk

---

Makefile

To make it easier to run some checks before pushing i added a makefile. You can use it with `make lint`, `make configs` or `make deps`. These are the same checks that run in github automaticly with each PR. Although it is possible to do checks with generate-images.sh i found this way more convenient. Thanks to @pktpls for providing this solution.

Adding Makefile for convenience

---

group_vars/model_netgear_wax202.yml
group_vars/model_zyxel_nwa55axe.yml

Snapshot uses the newer 5.15 Linux kernel. By switching the devices to snapshot the issues with unstable mesh connections are now gone.
Note: I did not include the ZyXEL NWA50AX into this commit, as it is seems to be used only as AP, however it will need to be switched to snapshot if someone wants to use it for meshing.

MT7915E: switch to snapshot

---

host_vars/wuhli-core/base.yml
host_vars/wuhli-n-nf-5ghz/base.yml
host_vars/wuhli-o-nf-5ghz/base.yml
host_vars/wuhli-s-nf-5ghz/base.yml
host_vars/wuhli-w-nf-5ghz/base.yml

freifunk_legacy was removed due to owe revert.

wuhli: fix non existing freifunk_legacy wireless profile

---

group_vars/model_avm_fritzbox_7530.yml
group_vars/model_avm_fritzbox_7530_dsa.yml

DSA conversion is neccessary to run OpenWrt snapshot so that we can test the VDSL modem.
Switch your host's `model` to `avm_fritzbox-7530_dsa` to try it out.

fritzbox7530: add dsa variant for snapshot

---

DEVELOPER.md
group_vars/model_tplink_tl_wdr3500_v1.yml
group_vars/model_tplink_tl_wdr3600_v1.yml
group_vars/model_tplink_tl_wdr4300_v1.yml
group_vars/model_tplink_tl_wdr4900_v1.yml
roles/cfg_openwrt/templates/common/config/swconfig.network.inc

Empty switch_ignore_ports-lists are no longer required in the model files. Removed it from the existing model-files and updated docs.

Added defaults for switch_ignore_ports

---

group_vars/location_scharni/networks.yml

1024 as metric is not enough to route the traffic via zwingli.

scharni: increase babeld metric to 2048 to prefer zwingli

---

group_vars/location_rhnk/networks.yml
host_vars/rhnk-nf-no-5ghz/base.yml
host_vars/rhnk-nf-nw-5ghz/base.yml
host_vars/rhnk-nf-so-5ghz/base.yml

- rhnk: rename APs and start to use them
- rhnk: add 60ghz klunkerkranich link, remove old test link
- rhnk: add wsw-60ghz sector for ak36
- rhnk: add some more notes and todos

rhnk: update definitions to match current deployment

---

.github/workflows/testbuild.yml

Before this a change of e16 caused a build of e16outdoor as well because a wildcard was used for the location. Now everything is more precise and duplicates also get removed.

workflow: make the detection of changed hosts and locations more robust

---

Makefile

Since the linter where moved the makefile wasn't working. Changed the path of the linters to its new folders.

Makefile: Updated position of linters in folder structure

---

host_vars/cafe-wostok-core/base.yml
host_vars/kts13-core/base.yml

kts13-core and cafe-wostock-core used a model-name with "avm_fritzbox-7530_dsa"", which doesnt exist resulting in an error. Fixed the modelnames by removing "_dsa".

Fixed modelnames for kts13-core and cafe-wostock-core

---

roles/cfg_openwrt/templates/corerouter/nftables.d/20-wg-maxseg-size.nft.j2

The switch to firewall4 made it necessary to check if we have 22.03 or snapshot when we create firewall rules. However, we forgot to check for 23.05. Since we abondned 21.02 we can remove the check for firewall4 completely.

templates: fix mss clamping for 23.05

---

roles/cfg_openwrt/templates/corerouter/config/dhcp.j2

This pull request enables the core router to announces routes to our IP networks (10.31.0.0/16, 10.36.0.0/16, 10.230.0.0/16) via DHCP option 121. This enables clients connected to multiple networks to reach Freifunk IPs without manually adding static routes.

dhcp: provision of static routes to Freifunk IPs

---

group_vars/model_ubnt_nanostation_m5_xw.yml

The nanostation m5 xw has 8 MB of flash and 64 MB of RAM and is not a tiny device. Without this fix firmware for the device can't be build.

models: nanostation m5 xw is not tiny

---

group_vars/location_bht/airos_dfs_reset.yml
group_vars/location_bht/networks.yml

Modify the timing for a dfs reset at bht to 0-23 (request from Carsten)
Give the link to Segen a worse metric since the link quality bht-segen is so poor.  This makes the preference for internet access to go over perleberger36->strom-gw.
This image has already been built and is currently runing on bht-core

bht: modify the dfs timing and metric at bht

---

roles/cfg_openwrt/tasks/main.yml

Added option so that the task is only executed when the wiki tag is given. Before it was executed every time.

Wikiupdater: Made execution optional

---

host_vars/l105-gw/gateway.yml

This interface was lost while being migrated to the bbb-configs.  Now it's back.  This system is already running on the vmhost and is routing traffic.

l105-gw: add eth1.32 interface to mesh with b.bbb-vpn

---

roles/cfg_openwrt/templates/common/config/network.j2
roles/cfg_openwrt/templates/common/config/wireless.j2
roles/cfg_openwrt/templates/corerouter/config/tunnelmanager.j2

This commit adds the 15 character limit check for bridge interfaces and adjusts the condition to actually check for 15 characters.  This resolves #185. The 15 character limit is mentioned here: https://openwrt.org/docs/guide-user/network/tunneling_interface_protocols

templates: check 15 character limit for bridges

---

.github/linters/.yaml-lint.yml

These two linters make sense for functional comments, e.g. when API documentation is generated from comments and a certain format and syntax needs to be enforced.
Our comments are purely for conveying free-form information to humans. We don't have a need for any specific formatting of comments.
The false-positive rate of the comment rules is obviously very high and leads to frustration that can be avoided at no cost. It's also not good practice to regularly ignore linter errors.
The latest example is #529
The best way forward is to not lint comments.

github: disable linting rules about comments

---

host_vars/ak36-gw/gateway.yml

Add comments for IPs of new ak36-teufelsberg and ak36-philmel60 devices as well as the strange hypervisor IP.
The respective mesh interface are commented out because the corerouter/gateway VM doesn't have them yet.

ak36: update IP and interface comments

---

group_vars/location_mahalle/networks.yml

The names were two long (max. 15 characters for name + "br-" prefix).

mahalle: shortened bridge name to fit limit

---

roles/cfg_openwrt/templates/corerouter/config/dhcp.j2

Add missing IPs (https://github.com/freifunk/icvpn-meta/commit/a5142788871802bd583f08d040957cb9ced9162e)

dhcp: add static routes to additional Freifunk IPs

---

locations/parzelle17-fritz.yml
locations/parzelle17.yml

This commit bringt the new location parzelle17, which is used for testing MT7915 meshing in a crowdy environment.

parzelle17: init location

---

group_vars/model_dlink_dap_x1860_a1.yml
group_vars/model_netgear_wax202.yml
group_vars/model_zyxel_nwa50ax.yml
group_vars/model_zyxel_nwa55axe.yml

Mesh is stable now in 23.05 with the latest fixes, therefore switch the devices over to 23.05

model: switch mt7915 devices to 23.05

---

group_vars/all/general.yml

- Digitalcourage updated their recommended addresses
- IPv6 for both Digitalcourage and FDN
- bug: AS250 anycast unreachable for us at L105

all: update dns servers and add ipv6

---

DEVELOPER.md
group_vars/location_cafe_wostok/networks.yml
group_vars/location_kts13/networks.yml
group_vars/location_rotelilly/networks.yml
host_vars/cafe-wostok-core/base.yml
host_vars/kts13-core/base.yml
host_vars/rotelilly-core/base.yml
roles/cfg_openwrt/templates/common/config/dsa.network.inc
roles/cfg_openwrt/templates/common/config/network.j2
roles/cfg_openwrt/templates/common/config/swconfig.network.inc
roles/cfg_openwrt/templates/common/sysctl.conf.j2
roles/cfg_openwrt/templates/corerouter/config/babeld.j2
roles/cfg_openwrt/templates/corerouter/config/dhcp.j2
roles/cfg_openwrt/templates/corerouter/config/firewall.j2
roles/cfg_openwrt/templates/corerouter/config/olsrd.j2
roles/cfg_openwrt/templates/corerouter/config/tunnelmanager.j2
roles/cfg_openwrt/templates/corerouter/config/tunspace.j2
roles/cfg_openwrt/templates/corerouter/firewall.user.j2
roles/cfg_openwrt/templates/corerouter/nftables.d/20-wg-maxseg-size.nft.j2

TunSpace is a new attempt at a client for wireguard tunnels - see freifunk-berlin/falter-packages#413 for the source code of TunSpace itself. The server side is still the same setup using wg-installer.
The preliminary syntax for this is:
```yml
role: corerouter
openwrt_version: 23.05-SNAPSHOT  # or snapshot
host__packages__to_merge:
- -tunnelmanager
- tunspace
- wireguard-tools
networks:
- vid: 50
role: uplink
- role: tunnel
ifname: ts_wg0
mtu: 1412
prefix: 10.31.123.42/32  # ipv6 prefix is always fe80::2/64
wireguard_port: 51820
mesh_metric_lqm:  # optional
- 'default 0.5'
mesh_metric: 256  # optional
- role: tunnel
ifname: ts_wg1
```
Please try it out, for me it has been working well for the past few days. Note that it currently logs to syslog *a lot* - this is intended, we'll make it …

networks: add tunnel role for use with tunspace

---

roles/cfg_openwrt/files/0001-image-fix-image-generation-within-ImageBuilder.patch
roles/cfg_openwrt/tasks/imagebuilder.yml

Include the fix for openwrt/openwrt#13881, it will take a few hours or days until fixed imagebuilder tarballs are available. When they are, this PR can be reverted.

imagebuilder: temporary fix for a few days

---

roles/cfg_openwrt/tasks/imagebuilder.yml

Make sure we apply that patch only for snapshot and 23.05

fixup: imagebuilder: temporary fix for a few days

---

group_vars/location_jup/networks.yml

Routing between segen and bht often went via jup. This adjustment fixes this.

jup: adjusted metrics of bad bht link

---

group_vars/location_klunker/networks.yml

Commentet out 5GHz Backup Link for now. This Link is still unused but will be left in config for further evaluation. When a decision is made it should be used again or removed.

location_klunker: disabled 5ghz backup link for now

---

group_vars/location_rio/networks.yml

the link towards emma is poor, therefore adjust mesh metrics so traffic from simeon flows via rhxb, rhnk towards emma

rio: adjust routing towards emma

---

.github/workflows/testbuild.yml
.gitignore
FAQ.md
README.md
generate-images.sh
roles/cfg_openwrt/tasks/add_symlinks.yml
roles/cfg_openwrt/tasks/fix_permissions.yml
roles/cfg_openwrt/tasks/imagebuilder.yml
roles/cfg_openwrt/tasks/main.yml
roles/cfg_openwrt/tasks/render_etc.yml

Working in /tmp is great because it's a ramdisk (fast & ephemeral), but it's also bad because it's a ramdisk (space-constrained & ephemeral). We can only build a few hosts at the same time, at a certain number we run out of diskspace (ramspace). That makes it hard to mass-test image builds locally, and it can also fail github builds, e.g. https://github.com/freifunk-berlin/bbb-configs/actions/runs/6445019125/job/17498618384
Instead we'll now build in ./tmp in the bbb-configs directory. While we're at it, clean up the various directory path variables.

ansible: move away from limited /tmp ramdisk, and clean up dir structure

---

group_vars/model_x86_64.yml
locations/pktpls.yml
vm.sh

Usage: ./vm.sh <location> [<imagedir>]
location  - Name of a BBB location config file stored at location/<location>.yml.
imagedir  - Image output directory of BBB-Configs, where *-generic-kernel.img
and *-generic-ext4-rootfs.img images for <location> can be found.
Default: /tmp/ansible-openwrt/tmp/imagebuild/<location>-core/bin/targets/x86/64
This script starts a Firecracker micro VM for a given BBB-Configs location's corerouter.
The VM starts very fast, doesn't need root permissions, and gives access to its console.
It exposes SSH/DNS/HTTPS and meshes over a Wireguard tunnel.
This VM is meant for development and debugging, and NOT for permanent deployment.
The VM location's corerouter must have `model: "x86-64"` and it needs registered
IP addresses, just like any regular location. To …

vm: add vm.sh script for fast rootless x86_64 VMs

---

group_vars/all/ssh-keys.yml

Lino proved to be a valuable member of our community by building new locations, doing a lot of work regarding documentation and issue tracking and by working on the new website. I think it is time to add his SSH key to the list of trusted keys, so he could help out even more.

all: add SSH key from Lino

---

roles/cfg_openwrt/templates/common/config/network.j2

This fixes #598 and enables untagged VLANs on devices without a switch, e.g. DAP-X1860 so the network port can be used to connect to an untagged network in an uplink configuration or to untag the DHCP network.

network: support untagged VLANs on devices without a switch

---

host_vars/fffw-lebenshilfe-core/base.yml

as @PolynomialDivision pointed out the package switch to tunspace was missing. This PR fixes this.

fffw-lebenshilfe: fix missing package change

---

host_vars/b0russia-core/base.yml
host_vars/borussia-core/base.yml
host_vars/casa-kua-core/base.yml
host_vars/fffw-lebenshilfe-core/base.yml
host_vars/forcki-core/base.yml
host_vars/habersaath-core/base.yml
host_vars/linie206-core/base.yml
host_vars/linksfraktiontk-core/base.yml
host_vars/mahalle-core/base.yml
host_vars/newyorck-core/base.yml
host_vars/sonnenblume-core/base.yml
host_vars/wuhli-core/base.yml
locations/cafe-wostok.yml
locations/elsekiehl.yml
locations/huette15.yml
locations/kirchhof.yml
locations/kts13.yml
locations/l5.yml
locations/muggel.yml
locations/noki.yml
locations/pktpls.yml
locations/rotelilly.yml
locations/suedblock.yml
roles/cfg_openwrt/tasks/conditional_packages.yml

Everything migrated to tunspace. So remove tunnelmaner completely and use a rule to automatically add tunspace to packages instead like previous done for tunnelmanager.

treewide: replace tunnelmanager with tunspace

---

locations/rhnk.yml

This fixes the nf APs. Without this the EAP225 uses too much power and does not account for the additional antenna gain. In addition this is required so mlk-nk can mesh again via 802.11s.

rhnk: fix nf APs and mesh

---

locations/parzelle17-fritz.yml

Testbuild fails due to handling of `-`, #670 would fix it

parzelle17-fritz: fixed location name

---

group_vars/model_mikrotik_routerboard_750gr3.yml

this currently affects sgfrd-core and vaterhaus-core. We should flash this on sgfrd-core first, since it's easier to access if something goes wrong, but this is a mt7621 target, so I don't expect any issues.
@Petrella please test this on sgfrd-core.

model: Mikrotik Routerboard 750gr3 bump OpenWRT version

---

.github/workflows/testbuild.yml
inventory/base_inventory

- Make inventory a little bit faster (= half as slow). Singlefile locations are slow to parse because it's a new python interpreter for every single host. This gets worse the more locations we convert to singlefile format. `yj` is a golang tool which has much faster startup. I'm not happy adding a non-python dependency, but I want to make this faster right now make it "pretty" later. Ideally we'd rewrite the inventory script in python - not starting any new interpreters means no need for a golang tool.
- only build if actual code has changed, not for any non-code changes
- only build configs, not full images
- this has been very time consuming and error prone when trying to merge PRs. we all have limited time and shouldn't spend it waiting for slow builds with limited value and …

Faster build times & little inventory fixes

---

locations/flughafen.yml

This antenna was unused and in station mode, therefore reconfigure it to be a south facing ap for people to connect.

flughafen: use 5ghz legacy station antenna as south AP

---

inventory/base_inventory

We have ~300 hosts in ~100 locations and we were calling `yq` multiple times for every single one of them. That was ~700 python interpreter invocations.
Now we only call it once to convert all YAML to JSON in one go, and let one `jq` script do all the merging. It's less code and much faster.
- Before: `ansible-inventory --list` 0m35,404s
- After: `ansible-inventory --list`  0m4,649s
- Without Ansible: `./inventory/base_inventory --list`  0m0,543s

inventory: back to acceptable performance

---

locations/teufelsberg.yml
locations/vaterhaus.yml

There are Meshtastic nodes connected to the USB-Ports of the two core routers. By installing USBIP packages on the core-routers we can remotely manage and update these nodes to new firmware versions. This was tested and both Meshtastic nodes now run the newest firmware.

teufelsberg, vaterhaus: USBIP packages for Meshtastic node management

---

group_vars/role_gateway/general.yml

I'm setting up a Cryptpad instance :lock:

gateway: allow inbound for cryptpad.berlin service

---

locations/strom.yml

(We're not using eth1/eth2 yet at the moment)

strom: add mellanox NIC driver

---

locations/ak36.yml

The antenna was decomissioned and removed

ak36: remove philmel60 antenna

---

.github/workflows/testbuild.yml
roles/cfg_openwrt/tasks/wikiupdater.yml
roles/cfg_openwrt/templates/common/wikiupdater.j2

Make the wikiupdater skript automaticly updates wikiarticles when a push happens to `master`. This will help keeping our wiki always up to date. I added the option `continue-on-error: true` so we will go on if no wikiarticle was found. In addition I created credentials for a `bbbot`. They are stored inside this repo in the envirement called [wikiupdater](https://github.com/freifunk-berlin/bbb-configs/settings/environments/1751983185/edit)

Include wikiupdater into testbuild action

---

group_vars/all/snmp_profiles.yml
locations/ak36.yml
locations/fesev.yml
locations/q216.yml
locations/spitta13.yml
roles/cfg_openwrt/templates/common/collectd/conf.d/bbb-snmp.conf.j2
roles/cfg_openwrt/templates/gateway/collectd/conf.d/bbb-snmp.conf.j2

This PR brings monitoring for Mikrotik SwitchOS and Ubiquitys Edgeswitches. In addition it fixes the monitoring of proprietary devices for our gateways.
- Fix Uptime Scale for Grafana freifunk-berlin/meta/issues/29
- Better Display Port Status in Grafana freifunk-berlin/meta/issues/29
- Better Display Port Speed in Gradana freifunk-berlin/meta/issues/29

snmp_profiles: add SwOs and Edgeswitch

---

group_vars/model_dlink_covr_x1860_a1.yml

This PR adds support for D-Link COVR-X1860 A1 devices.

model: add dlink-covr-x1860-a1

---

group_vars/all/snmp_profiles.yml
locations/agym.yml
locations/chris.yml
locations/dorfplatz.yml
locations/dtmb.yml
locations/emma.yml
locations/gruni73.yml
locations/j41.yml
locations/jup.yml
locations/kiehlufer.yml
locations/kirchhof.yml
locations/klunker.yml
locations/l105.yml
locations/l5.yml
locations/ohlauer.yml
locations/saarbruecker.yml
locations/sama.yml
locations/segen.yml
locations/strom.yml

This PR adds Monitoring for some switches and several new profiles to archive this. These changes got already deployed at the gateways. Grafana/cgp arent yet at the state of showing all of these values in a beautifull way but this shouldnt stop us from slowly rolling out more data collection from the switches.
Although i didnt touched it Im unhappy about the current `airos_6` Situation. When no Station is connected  to a AirOS 6 AP the snmp-call for the name of the connected stations obviously cant work resulting in a NoSuchName-Error in our logs. This means that we get at e.g. `chris-core` every 30 seconds 30 errors. We should address this in the future. #766 
TODOs:

Treewide: Add snmp monitoring for some switches

---

.github/workflows/configrun.yml
.github/workflows/linter.yml
.github/workflows/testbuild.yml
.github/workflows/wikiupdate.yml

Move the wikiupdate-workflow into a independent file making it way more clean. And it is working now as intended (instead of building all locations) as you can see here
[with a changed location](https://github.com/FFHener/bbb-configs/actions/runs/7807563218/job/21296175674)
[without a changed location ](https://github.com/FFHener/bbb-configs/actions/runs/7807593320/job/21296262014)
I use `||true` so the task will never fail because there might be locations that doesn't get updated because they don't have a wikiarticle.
In addition i bumped the version of `actions/checkout@v3` to v4 as the old one was using Node.js 16 which is deprecated.

workflows: fix wikiupdate and bump version to v4

---

roles/cfg_openwrt/templates/common/rc.local.j2

When collectd wants to get the Names of Stations via snmp connnected to a device running AirOS 6 that have none connected it reports a "NoSuchName" error to logd resulting in a lots of logspamming. At chris-core it was 60 per minute.
This Script will change the option "procd_set_param stderr  1" to "0" in the file /etc/init.d/collectd to deactivate logging of all errors. The monitoring will still work. I prefer not having logs over logspamming as the logfiles will get useless otherwise. It is still possible to change this option back to 1 until next boot to get a better insight when debugging collectd-issues.
This fixes #766

templates: deactivate stderr of collectd if it monitors airos_6

---

locations/mela-2g.yml
locations/mela.yml
locations/torte-mela-2g.yml

This PR recovers the second part of the mela installation. The old core router is still broken and need to be replaced. Due to the fact that we have 2 switches the installation is now split in half.

mela: 2g uplink, second core until install is fixed

---

.github/workflows/configrun.yml
locations/zwingli.yml

We added a meshtastic node to zwingli and this adds the packages required to mange it remotely.
The artifact upload is broken due to files with colons, the workflow needs to be adjusted / fixed.

zwingli: add packages to manage meshtastic node

---

locations/rauchhaus.yml

This fixes freifunk-berlin/meta#45.
I will flash as soon as I have contact to the people at the location.

rauchhaus: add second mesh vlan

---

locations/xdorf.yml

This fixes freifunk-berlin/meta#44.
I switched the device, because I had a 4040 available. It is flashed and pwd is set, ready to be replaced as soon as I get contact to people from the location.

xdorf: replace core router

---

locations/newyorck.yml

This is the proposal for a new Freifunk installation at the NewYorck site. If everything fits and is approved, please convert to a draft so that it is not accidentally merged before it has been deployed.

newyorck: init location

---

group_vars/version_snapshot.yml

That means the tarball filename ends in `.zst` now (but not for 22.03 and 23.05)
https://github.com/openwrt/openwrt/commit/2496f436a837f4d56a13883497ab5d07fb01d0f7

imagebuilder: OpenWrt snapshot now uses Zstd instead of xz-utils

---

locations/newyorck.yml

There were reports of different kind of problems for clients to connect. I now simplified the wireless setup by:
- removing the roaming feature, because this seems to be the problem that made some aps unresponsive (issue for that coming soon)
- use same freifunk wireless profile as the default, so that owe transition should not make problems
- remove mesh, as it is not needed for the indoor antennas
This new version is running for about 5 days now and seems to have fixed the problems.

newyorck: simplify wireless

---

locations/ak36.yml

This Ubiquiti sector antenna was already pretty old and has never seen any connections. It was removed from the mast a few weeks ago.

ak36: remove friedenau sector antenna, never used

---

locations/emma.yml
locations/radbahn.yml

:candle: :pray: 
> The OKOD - OpenWrt Kiss of Death - strikes again.
>
> We don’t know why, we don’t know when;
> but it’s only a matter of time,
> before OKOD strikes another poor RT3200 again.
> All was once well, but that was only then;
> once it was five, but five became ten.
> So we ain’t got no zen,
> knowing OKOD will strike for sure anytime again.
> WiFi 6, tricks and nice cake-mix, but too many bricks;
> we therefore place all our hope in [daniel](https://forum.openwrt.org/u/daniel) and [his promised fix](https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/4002).
>
> *-- Lynx https://forum.openwrt.org/t/belkin-rt3200-linksys-e8450-wifi-ax-discussion/94302/4085*
---
- Bring in new Fritzbox 4040 as corerouter. The Belkin RT3200 self-bricked and needs to …

emma: new corerouter, two 60ghz cubes, and radbahn tweaks

---

locations/radbahn.yml

Tomorrow is Mayday, and Radbahn is in the middle of Kreuzberg... let's up the DHCP range from 128 to 256 addresses.
The Zyxel APs can do 256 clients each (128 per radio interface) but config.berlin.freifunk.net failed to give me a /23 :-)

radbahn: bigger IP range for Mayday

---

locations/karanfil.yml

https://hopglass.berlin.freifunk.net/#!v:m;n:karanfil-core.olsr

karanfil: init location

---

locations/pktpls.yml
roles/cfg_openwrt/templates/common/config/dsa.network.inc
roles/cfg_openwrt/templates/common/config/network.j2
roles/cfg_openwrt/templates/common/config/swconfig.network.inc
vm.sh

The network templates cover three possible port configs:
- Switch chip with DSA driver: `switch0`
- Switch chip with swconfig driver: `eth0` (usually)
- No switch chip: `eth0` (usually)
This patch adds the possibility of a fourth port config,
where an additional physical port can be used for individual VLANs.
Examples include 4G USB sticks, devices without a switch chip but with
multiple ports, etc.
The `vm.sh` script now offers uplink on both `eth0.50` and `eth1`.
We also simplify the whole `port` logic a little bit.
Bonus: this will also make it easier to refactor how we define gateways locations.

network: allow other ports in addition to eth0

---

locations/weidenbaum.yml

weidenbaum-r0 is connected via LAN but not setup as a standalone router that meshes via LAN. The reason for this is that we had issues with flashing Ubiquiti UniFi AC Mesh devices and bricked them in the process. We did not want to risk this today. This might be changed in the future. We also keep the mesh on the core router active as a backup, but make the metrics worse so routing via weidenbaum-r0 is preferred. ~~There might also be an opportunity to connect to chris-core, but we had no antenna at hand to test this out, but already prepared the configuration to test this out.~~

weidenbaum: init location

---

locations/rhnk.yml

Set LQM to prevent that hermann12 is used as an uplink.

rhnk: set LQM for hermann12-core

---

locations/magda.yml

0.5 is not enough to prevent liese-11-sw-core to become a gateway.
Fixes: 87b2c9fc70de ("magda: liese-11-sw-core lqm")

magda: reduce lqm to 0.2 to liese-11-sw-core

---

group_vars/all/general.yml

- Add Quad9 "recommended" servers (malware blocking enabled, DNSSEC validation enabled).
- Remove AS250.net which has been broken at L105 for a long time.
- Remove digitalcourage.de, they offer only DNS-over-TLS, which we're not prepared for at the moment.
dnsmasq picks random upstream server for every incoming DNS request. The timeout before it tries the next seems to be around 5 seconds.
Removing the broken upstream servers will improve UX significantly.

all: update the upstream DNS servers

---

group_vars/model_ubnt_unifiac_mesh.yml

Cherry-picking this fix from #889

model: ubnt unifiac mesh: fix 2.4 ghz path

---

.github/checks/check-ip-prefix-duplicates.sh
.github/workflows/check-ip-prefix-duplicates.yml
locations/habersaath.yml
locations/noki.yml

This ensures that we do not have duplicate IP prefixes any more:
closes https://github.com/freifunk-berlin/bbb-configs/issues/901

workflows: add ip prefix duplicate check / fix duplicates

---

locations/weidenbaum.yml

not flashed yet. this requires a two step flash process via a minimalistic image.

weidenbaum: make weidenbaum-r0 an AP

---

group_vars/all/general.yml
roles/cfg_openwrt/templates/common/collectd/conf.d/basic.conf.j2

Right now we only monitor IPv4 pings, but I think IPv6 would interesting as well especially because we use different routing protocols for them. The IPv6 address is from Cloudflare as well to make them comparable.

Collectd: Adding ping monitoring for IPv6 

---

locations/fardf.yml

This PR is a first draft for converting fardf to bbb-configs based on the current setup, not following the bbb-configs conventions. The main motivation for this PR is to solve the instability issues with the current Falter firmware running at the core.
TODO:
The migration would be as follows:
After bbb-configs migration:

fardf: init location

---

group_vars/all/imageprofile.yml
group_vars/version_snapshot.yml
locations/pktpls.yml
roles/cfg_openwrt/tasks/conditional_packages.yml

The falter-packages main branch has stabilized, it's now again safe to pull in falter-common.

version: switch snapshot back to snapshot feed

---

group_vars/all/general.yml
locations/huette.yml
locations/hway.yml
locations/kiehlufer.yml
locations/kub.yml
locations/radbahn.yml
locations/suedblock.yml
roles/cfg_openwrt/templates/common/config/system.j2

There's been a lot of progress on mt76 wifi bugs recently. Fewer crashes, fewer meshing issues. https://github.com/openwrt/mt76/commits/master/
The custom imagebuilder I used has the latest commit from openwrt/mt76.git and also a few kernel options for debugging: https://github.com/pktpls/falter-builter/commit/b2eaa19b8f74a7c7bd5c791fcd44af9d7dbfb6b6

all: mt76 driver debugging

---

group_vars/role_gateway/general.yml

So nbd can access it and gather data live. Already applied on ohlauer-gw and saarbruecker-gw.

gateway: allow incoming to radbahn, for mt76 debugging

---

locations/ak36.yml

Add a v6 address to the ak-gw.
The router will announce a default route and accept the announcement of the /44s but won't propagate them to the IXes

ak36-gw: add v6 uplink

---

group_vars/model_ubnt_bullet_m2_ar7241.yml
group_vars/model_ubnt_bullet_m5_ar7241.yml
locations/jup.yml
locations/ska95.yml

We have a bunch of Nanostation M5/M2 Loco XM 1 with only 1 ethernet port. The installation section for these devices states that they will be bricked when installing the latest Nanostation firmware and instead the Bullet M firmware should be used (https://openwrt.org/toh/ubiquiti/nanostationm5#installation). This PR creates a model file for a 2.4 GHz and 5 GHz version that can be used and works with the devices we have so they can be deployed in the field.

model: Nanostation Loco XM (1 port) support for both 2.4 and 5 GHz

---

roles/cfg_openwrt/tasks/conditional_packages.yml

these packages add to the size of the image that will be uploaded to /tmp/ and should therefore be removed for low_mem.

packages: no debug packages with low_mem

---

group_vars/all/imageprofile.yml
roles/cfg_openwrt/templates/corerouter/config/olsrd6.j2
roles/cfg_openwrt/templates/gateway/config/olsrd6.j2

Not kidding...
Quick procedure to deploy without reflashing:
```
rm -r tmp
ansible-playbook play.yml -t config -l sama-core,zwingli-core
cd tmp/configs
for i in *; do scp -O $i/etc/config/olsrd6 root@$i.olsr:/etc/config/; ssh root@$i.olsr /etc/init.d/olsrd6 start; ssh root@$i.olsr /etc/init.d/olsrd6 enable; done
```

Configure olsrd6 in order to fix traceroute name lookup

---

group_vars/role_corerouter/imageprofile.yml
roles/cfg_openwrt/files/common/iproute2/rt_tables
roles/cfg_openwrt/files/corerouter/babeld.conf
roles/cfg_openwrt/files/corerouter/bird.conf
roles/cfg_openwrt/files/corerouter/iproute2/rt_tables
roles/cfg_openwrt/templates/common/config/network.j2
roles/cfg_openwrt/templates/corerouter/config/olsrd.j2

Implement following changes which are preparing the migration towards using babel also for IPv4 - #964
- Add new Routing Tables to avoid babel routes compete with olsrd, which could lead to routing loops. We have to ensure that the routes get installed only in the appropriate tables, never in the default/main.
```
babel-default # Contains default routes from babel
babel-ff # Contains freifunk routes (hna) from babel
olsr-default # Contains default routes from olsr
olsr-ff #  Contains freifunk routes (hna) from olsr
```
- Setup routing policy in following order:
```
babel-ff -> olsrd-ff -> babel-default -> olsrd-default
```
- Ensure that olsrd and babeld install IPv4 routes only in the appropriate tables. Unfortunately babeld is not able to install routes in different policies, therefore …

Implement IPv4 Route Policy to prefer babel routes

---

roles/cfg_openwrt/templates/corerouter/config/olsrd6.j2
roles/cfg_openwrt/templates/gateway/config/olsrd6.j2

This PR changes the suffix for olsrd6 also to olsr instead of olsr6 so a connections or trace to a remote node can always be established using the same hostname.
```
root@w38b-core:~# mtr -r -b -w -4 k12-core.olsr && mtr -r -b -w -6 k12-core.olsr
Start: 2024-09-20T18:23:00+0200
HOST: w38b-core                               Loss%   Snt   Last   Avg  Best  Wrst StDev
1.|-- mid5.sama-core.olsr (10.31.79.182)       0.0%    10    1.8   1.8   1.5   2.2   0.2
2.|-- mid3.saarbruecker-gw.olsr (10.31.83.57)  0.0%    10    3.9   3.8   2.3   7.8   2.0
3.|-- segen-core.olsr (10.31.6.64)             0.0%    10    9.5   5.1   2.7   9.5   2.1
4.|-- k12-core.olsr (10.31.158.133)            0.0%    10    6.1   7.7   4.4  15.6   3.8
Start: 2024-09-20T18:23:15+0200
HOST: w38b-core …
```

olsrd: unify suffix

---

locations/ak36.yml

Das alte vlan war auf dem switch nur auf:
- ak-gw
- ak36-testbox1g
- ak36-testbox10g
verbunden
eth2 ist nun der direkte link zu: https://github.com/freifunk-berlin/bbb-configs/blob/main/locations/strom.yml#L85

bbbvpn is on another interface

---

locations/emma.yml

Fritzbox was not a good replacement for the bricked corerouter in April, but it was the only device I had at hand. It has regular crashes and outages, so bad that we're force-rebooting it every hour. We knew that before, but there was no time to grab a better device.
Now switch to a Routerboard 750gr3, which isn't as fast as the previous Belkin RT3200, but is rock solid stable.

emma: new corerouter, fritzbox again unstable

---

mass-update.sh

script should switch to next debug output right after the device becomes unavailable

scripts: improve mass-update script

---

roles/cfg_openwrt/tasks/wikiupdater.yml

Get rid of the dirty way the variable was constructed to make it work with locations that have a `-` in their name

wikiupdater: fix building of variable

---

roles/cfg_openwrt/templates/common/config/network.j2
roles/cfg_openwrt/templates/libraries/network.j2

In order to avoid code redundancy i factored out some of the lookup code of config/network.j2 into macros in libraries/network.j2.
I did not fix indentation of config/network.j2, except the ones which affect the output.
--check --diff run results for /etc/config/network:
wilgu10-int:
```
--- before: /home/spolack/git/bbb-configs/tmp/configs/wilgu10-int/etc/config/network
+++ after: /home/spolack/.ansible/tmp/ansible-local-216624zq1d7khx/tmpcf1vd_xh/network.j2
@@ -1,9 +1,8 @@
-
config rule6
option priority 33000
-        option lookup 'babel-src'
+	option lookup 'babel-src'
config rule
@@ -11,15 +10,15 @@
option lookup 'babel-ff'
config rule
-        option priority 33101
-        option lookup 'olsr-ff'
+	option priority 33101
+	option lookup 'olsr-ff'
config rule
option priority 33200 …
```

Refactor some common network config features into libnetwork

---

roles/cfg_openwrt/templates/common/nftables.conf.j2

(if and endif are the only changes, the rest is indentation fixes.)
Intermittently breaks routed IP traffic to mesh neighbours if the mesh interface is using the underlying (wifi) interface directly, instead of a bridge or VLAN.
The filter is supposed to learn our own mac addresses from outgoing traffic and then reject incoming reflected packets with our own src address. If we don't filter these, logread gets cluttered with informational messages saying "received packet with our own address".
However, if a mesh interface uses the underlying interface directly (instead of wrapping it in a bridge or VLAN), we somehow end up blocking our mesh neighbours. This is the case e.g. on corerouters that mesh on their own, with integrated antennas.
For now let's "fix" this by not using the reflection …

nftables: omit reflection filter on corerouters

---

locations/ak36.yml
locations/dragonkiez-adlerhalle.yml
locations/dragonkiez-buero.yml
locations/dragonkiez-dorfplatz.yml
locations/dragonkiez-kiezraum.yml
locations/dragonkiez-rathausblock-miami.yml
locations/l105.yml
locations/ohlauer.yml
locations/saarbruecker.yml
locations/strom.yml
locations/w38b.yml
locations/zwingli.yml

Looks like metric was renamed to mesh_metric at some point to be identical accross gateways and corerouters, without properly adjusting all config files:
https://github.com/freifunk-berlin/bbb-configs/blob/28dbaf6b4ea99a6dbd392ac7fc575e82cbcd91fa/roles/cfg_openwrt/templates/gateway/config/babeld.j2#L22
https://github.com/freifunk-berlin/bbb-configs/blob/28dbaf6b4ea99a6dbd392ac7fc575e82cbcd91fa/roles/cfg_openwrt/templates/corerouter/config/babeld.j2#L21
This PR fixes this so we generate proper babeld config files. In addition this fixes the mesh metric at w38b that was still to high.

Fix mesh metrics

---

DEVELOPER.md
group_vars/all/wireless_profiles.yml
locations/colbe15.yml
locations/dragonkiez-buero.yml
locations/ekke.yml
locations/hts4.yml
locations/hway.yml
locations/kiehlufer.yml
locations/kirchhof.yml
locations/koepi.yml
locations/muggel.yml
locations/newyorck.yml
locations/noki.yml
locations/q216.yml
locations/radbahn.yml
locations/rauchhaus.yml
locations/stadalbert.yml
locations/tempelwg.yml
locations/w38b.yml
locations/wilgu10.yml
roles/cfg_openwrt/templates/common/config/wireless.j2
roles/cfg_openwrt/templates/common/nftables.conf.j2

The `legacy_rates` and `country` options are declared in a boilerplate way all over the tree. Create sane defaults and remove the unnecessary declarations from the tree.

Clean up wireless devices defaults

---

locations/huette.yml
locations/hway.yml
locations/kiehlufer.yml
locations/kub.yml
locations/radbahn.yml
locations/suedblock.yml

(Except on radbahn-w-nf and radbahn-o-nf, which I'll monitor for a while longer.)

treewide: remove mt76 debugging

---

locations/walde.yml

Note: The mgmt-IP is currently set to 192.168.x.x for `walde-emma`

walde: fix ip in snmp_section for walde-emma

---

group_vars/all/imageprofile.yml
group_vars/target_ipq40xx_generic
locations/huette.yml
locations/hway.yml
locations/kiehlufer.yml
locations/kub.yml
locations/radbahn.yml
locations/suedblock.yml

There was a time when MbedTLS was already the default in OpenWrt, but didn't yet support everything that we needed.
It does now. I have been testing it on a few busy locations for a few months.

imageprofile: return to MbedTLS

---

roles/cfg_openwrt/templates/common/collectd/conf.d/basic.conf.j2

collectd: only load iwinfo plugin on non low_mem or _flash devices

---

locations/segen.yml

This change is to prevent k12-h4-core and k12-h1-core from sometimes routing via 2GHz mesh links. Before this change the metrics for the following paths were identical:
5 GHz: segen <-> k12-h2 <-> k12-h1/h4
2 GHz: segen <-> k12-h1/h4

segen: adjust mesh metrics

---

group_vars/all/imageprofile.yml

We removed px5g in 4f29940 without making sure there's another variant of it installed. Pull in the default via luci-ssl.

imageprofile: fix TLS certificate generation

---

group_vars/all/general.yml
roles/cfg_openwrt/templates/corerouter/bird.conf.j2

this makes the metric of 2GHz mesh links worse than 5GHz mesh links by adding the default metric.
In addition to this we need to adjust metrics at various locations where 802.11s links have metrics manually set below 2048 as the new default of 2048 for 802.11s changes routing at various locations.

birdc: metrics penalty for 2GHz adhoc

---

group_vars/role_corerouter/imageprofile.yml
roles/cfg_openwrt/templates/corerouter/bird.conf.j2

corerouter: use patched version of bird2 and add proper inbound metrics

---

locations/bht.yml
locations/jup.yml

This fixes the routing in the triangle bht<->jup<->segen and also assures that bht routes via perleberger36->strom instead of using segen->saarbruecker.

bht, jup: fix routing

---

roles/cfg_openwrt/templates/corerouter/bird.conf.j2
roles/cfg_openwrt/templates/gateway/bird.conf.j2

IPv4 Default Route via Babel 

---

roles/cfg_openwrt/templates/ap/config/firewall.j2

The AP image doesn't contain a firewall package or firewall settings. When installing the firewall later on, it loads default settings and locks us out of the device permanently.
Add a basic firewall config allowing mgmt access, just to prevent this improbable but unfortunate case.
(This happened at Teufelsberg the other week, people needed to go there to fix it.)

ap: prevent lockout when installing firewall later

---

locations/simeon.yml

Meta-Issue dazu: https://github.com/freifunk-berlin/meta/issues/133

simeon: swap core router

---

locations/elsekiehl.yml

It's never been used, and tunspace with an absent uplink currently produces a memory leak in bird2. Let's just remove tunspace here, it can be added back if/when the uplink materializes.

elsekiehl: remove unused tunspace setup

---

locations/rigaer78.yml

With https://github.com/freifunk-berlin/bbb-configs/commit/58b894c641b9a3608b9c3bac93e35e0571133ae8 we can now configure VLAN tagging using the bridge names.
I logged in into the APs and copied the tagging from the existing APs and it differs from the current config, indicating that the config is not in sync and might need to be checked more carefully. In addition the Siemens AP does not have that many ports.

rigaer78: migrate port untagging to using named bridges

---

roles/cfg_openwrt/templates/gateway/config/firewall.j2

gateways: allow traffic towards inbound_filtered networks

---

group_vars/role_gateway/imageprofile.yml
roles/cfg_openwrt/templates/gateway/bird.conf.j2
roles/cfg_openwrt/templates/gateway/config/network.j2
roles/cfg_openwrt/templates/gateway/config/olsrd.j2

This involves few changes:
* Move IPv4 Static default route into bird, thus delete it from main network config
* Fix OLSR messing with policy routing (by setting its priorities super high)
* Remove OLSR dyngw which doesnt work with our policy routing approach and create a static default route HNA instead.

gateways: fix olsrd->babel soft migration

---

locations/ilr.yml
locations/kitty.yml
locations/sav.yml

With https://github.com/freifunk-berlin/bbb-configs/commit/58b894c641b9a3608b9c3bac93e35e0571133ae8 we can now configure VLAN tagging using the bridge names.

ilr, kitty, sav: simpler VLAN untagging

---

.github/workflows/linter.yml
inventory/README.md
inventory/base_inventory
inventory/keyed_groups_stage_1.config

I've had this written down since January :grimacing: and gave it some more polish

Inventory docs

---

group_vars/model_avm_fritzbox_7320.yml
group_vars/model_comfast_cf_e130n_v2.yml
group_vars/model_comfast_cf_ew72.yml
group_vars/model_glinet_gl_ar300m_nor.yml
group_vars/model_speedport_w_504v_typ_a.yml
group_vars/model_tplink_eap225_outdoor_v3.yml
group_vars/model_tplink_tl_mr3020_v3.yml
locations/hdk-0.yml
locations/hdk-13.yml
locations/hdk-17f.yml
locations/hdk-23.yml
locations/hdk-24.yml
locations/hdk-39.yml
locations/hdk-42.yml
locations/hdk-47a.yml
locations/hdk-48.yml
locations/hdk-53.yml
locations/hdk-54.yml
locations/hdk-59.yml
locations/hdk-64.yml
locations/hdk-66b.yml
locations/hdk-78a.yml
locations/hdk-8.yml
locations/hdk-80.yml
locations/hdk-85b.yml
locations/hdk-88m.yml

This adds the remaining locations and models from HDK. Besides this we will need to rework the conditional packages to reduce the image size for some models, but this will be a different PR.

Hdk add locations and models

---

group_vars/model_tplink_eap225_outdoor_v1.yml
group_vars/model_ubnt_unifiac_mesh.yml

Already running at multiple locations (e16outdoor, funkigel, hdk-30).

Promote TP-Link EAP225 v1 and Ubiquiti UniFi AC Mesh to OpenWRT 24.10

---

locations/funkigel.yml
locations/hdk-0.yml
locations/hdk-13.yml
locations/hdk-30.yml
locations/hdk-64.yml
locations/hdk-66b.yml
locations/w38b.yml
locations/weidenbaum.yml

Without this 24.10 nodes have issues meshing with older nodes via 2.4 GHz

hdk,w38b,weidenbaum,funkigel: enable legacy_rates

---

group_vars/model_cudy_x6_v1.yml
group_vars/model_x86_64.yml
group_vars/model_zyxel_nwa50ax.yml
locations/hway.yml
locations/suedblock.yml

I updated the following:
This also included some Fritzboxes 4040/7530 and SXTsq 5 ac, which have already been bumped in the repo

model: bump zyxel_nwa50ax & cudy_x6-v1 & x86-64 to 24.10

---

mass-update.sh

scripts: improve mass update script

---

locations/rhnk.yml

This PR renames the p2p devices and corresponding mesh networks to make it easier to understand.

rhnk: rename p2p devices and mesh networks

---

group_vars/all/general.yml
locations/elsekiehl.yml
locations/huette.yml
locations/hway.yml
locations/kiehl71.yml
locations/kiehlufer.yml
locations/kub.yml
locations/simeon.yml
locations/wilde.yml
roles/cfg_openwrt/templates/common/config/system.j2

Treewide: Set 'log_size' to 1024 except devices with small memory

---

locations/magda.yml

This adds an additional DHCP network without `inbound_filtering` for client devices attached by cable.
There's also a new Mikrotik PoE switch downstairs, replacing the SFP/GbE media converter. It's configured to have the new VLAN 41 untagged on all non-magda-ports.

magda: add switch & public DHCP network

---

group_vars/all/wireless_profiles.yml
locations/colbe15.yml
locations/ekke.yml
locations/hts4.yml
locations/hway.yml
locations/kiehlufer.yml
locations/koepi.yml
locations/newyorck.yml
locations/noki.yml
locations/q216.yml
locations/rauchhaus.yml
locations/stadalbert.yml
locations/tempelwg.yml
locations/wilgu10.yml

`ieee80211w: 1` does not work with quite some devices, mainly windows based devices but changing it to `ieee80211w: 2` always worked. I therefore suggest to change this to `ieee80211w: 2` as new default as it solved compatibility issues for me. Let me know if you have any concerns.

all: change ieee80211w to required

---

group_vars/role_gateway/general.yml

- Remove prometheus-poc (RIP)
- Remove radbahn mt76 debugging (RIP)
- Allow SSH for a magda client

gateway: update firewall port openings

---

group_vars/all/general.yml
roles/cfg_openwrt/templates/ap/config/firewall.j2
roles/cfg_openwrt/templates/corerouter/config/firewall.j2
roles/cfg_openwrt/templates/gateway/config/firewall.j2

Add option to enable flow offloading:
https://openwrt.org/docs/guide-user/perf_and_log/flow_offloading
this massively improves the routing performance on several devices
e.g.:
- Fritzbox 7530 from ~250 Mbits bidirectional to 500 (limited by the cpu that is connected only via gigabit to the switch)
- EX400 from ~200Mbits to ~950 bidirectional when using both interfaces
Because of the pitfalls mentioned in the wiki page i would like to test this on a few selected sites

templates: add option to enable flow offloading

---

roles/cfg_openwrt/templates/common/config/dsa.network.inc
roles/cfg_openwrt/templates/corerouter/config/tunspace.j2
roles/cfg_openwrt/templates/libraries/network.j2

Only use bridges with switch ports devices. Remove bridge in DSA configurations, as it causes roaming issues.
Maybe before checking int_port we could also check for dsa_ports.

templates: fix roaming bug by avoiding bridge in DSA setups

---

locations/hway.yml
locations/podone.yml
locations/podtwo.yml

For experiments with mesh-networked podman containers/vms.
Useful to have it in the main branch so the gateways add them to firewall lists.

init podone and podtwo

---

roles/cfg_openwrt/templates/libraries/network.j2

Running 802.11s mesh directly on a core router caused OLSR to handle meshing because the Bird configuration was incorrect. This patch fixes the issue by checking for core routers in the library functions and selecting the interface name accordingly.
Fixes: 7f523e8f9934 ("templates: fix roaming bug by avoiding bridge in DSA setups")

templates: network: fix meshing with Bird on core routers

---

locations/emma.yml

- Replace the four switches with a Mikrotik CRS328 (24x GbE, 4x SFP+)
- Replace corerouter with Thinkcentre+Mellanox, connected to switch with SFP+
- Add a cheap local mgmt AP
A follow-up PR will clean up the mesh names and possibly add/replace mesh antennas.

emma: new corerouter, new switch, new mgmt AP

---

group_vars/model_cudy_ap3000_v1.yml
group_vars/model_cudy_ap3000outdoor_v1.yml
group_vars/model_cudy_wr3000h_v1.yml

The Cudy models are supported in 24.10 for some time now. This PR switches the models from snapshot to 24.10 for more stable builds. Users can keep using snapshot for individual locations by specifying it in the location yml file.

model: use 24.10 instead of snapshot for cudy models

---

group_vars/all/general.yml
group_vars/role_corerouter/general.yml
group_vars/role_gateway/general.yml
roles/cfg_openwrt/tasks/imagebuilder.yml
roles/cfg_openwrt/tasks/merge_vars.yml
roles/cfg_openwrt/templates/common/config/network.j2

merge_vars: fix shared-prefix conflicts
Example: the suffix "files__to_merge" also matches
"wireless_profiles__to_merge" which caused funny issues.
Let's also match on the leading underscores to prevent that.
group_vars/all/general.yml             |  2 +-
group_vars/role_corerouter/general.yml |  2 +-
group_vars/role_gateway/general.yml    |  2 +-
roles/cfg_openwrt/tasks/merge_vars.yml | 14 +++++++-------
4 files changed, 10 insertions(+), 10 deletions(-)
render_etc: fix file permissions syntax
roles/cfg_openwrt/tasks/render_etc.yml | 6 +++---
1 file changed, 3 insertions(+), 3 deletions(-)
network: fix stray ip6addr option
This piece was outside of the corresponding `network` UCI block.
In certain cases this `ip6addr` option was printed alone.
This means it was parsed as if it belonged …

Fix smallies

---

README.md

This was reported by 2 people trying to generate images with bbb-configs. There is apparently a problem with the kernel, so generating in a vm didnt worked as well.

README: Add hint to avoid using Apple M Chips as they wont work
